#ifndef LEVELS_H
#define LEVELS_H

//#define TEST_MODE

#define CAVE01_LEVEL_ID 0
#define CAVE01_ROW_SIZE 10
#define CAVE01_COL_SIZE 10
extern char CAVE01[CAVE01_ROW_SIZE][CAVE01_COL_SIZE+1];
#define CAVE01_ENTRANCE_ROW 0
#define CAVE01_ENTRANCE_COL 0

#define CAVE02_LEVEL_ID 1
#define CAVE02_ROW_SIZE 15
#define CAVE02_COL_SIZE 15
extern char CAVE02[CAVE02_ROW_SIZE][CAVE02_COL_SIZE+1];
#define CAVE02_ENTRANCE_ROW 0
#define CAVE02_ENTRANCE_COL 2

#define TEST_LEVEL CAVE01_LEVEL_ID

#define CAVE03_LEVEL_ID 2
#define CAVE03_ROW_SIZE 20
#define CAVE03_COL_SIZE 20
extern char CAVE03[CAVE03_ROW_SIZE][CAVE03_COL_SIZE+1];
#define CAVE03_ENTRANCE_ROW 0
#define CAVE03_ENTRANCE_COL 1

// 아래에 loading하기를 원하는 레벨의 ID를 카피하면 된다.
#define TEST_MODE_LEVEL_ID CAVE01_LEVEL_ID

#define HERO_ENTRANCE_ROW CAVE01_ENTRANCE_ROW
#define HERO_ENTRANCE_COL CAVE01_ENTRANCE_COL

#endif
